# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Timetable"
  url = "#timetable"
  weight = 20

[[main]]
  name = "Schedule"
  url = "#schedule"
  weight = 30

[[main]]
  name = "Syllabus"
  url = "#syllabus"
  weight = 40
  
[[main]]
  name = "Project"
  url = "#project"
  weight = 50

[[main]]
  name = "Help"
  url = "#help"
  weight = 60
  
[[main]]
  name = "People"
  url = "#people"
  weight = 70

[[main]]
  name = "Resources"
  url = "#resources"
  weight = 80
  
[[main]]
  name = "<i class='fab fa-github'></i>"
  url = "https://github.com/ids-s1-19"
  weight = 90

[[main]]
  name = "<i class='fab fa-r-project'></i>"
  url = "https://rstudio.cloud/spaces/34062/projects"
  weight = 100

[[main]]
  name = "<i class='ai ai-piazza'></i>"
  url = "https://piazza.com/ed.ac.uk/fall2019/math08077/home"
  weight = 110
  menu_align_right = true

[[main]]
  name = "<i class='fas fa-play-circle'></i>"
  url = "https://www.learn.ed.ac.uk/webapps/osc-BasicLTI-BB5d1b15b77a8ac/tool.jsp?course_id=_75012_1&content_id=_4298466_1"
  weight = 120
  menu_align_right = true
